server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raydeng83/config-repo/
          username: raydeng83
          password: Rochester24
          search-paths: itemservice, userservice, listingservice, leaseservice, authenticationservice

        encrypt:
          enabled: false
